### Successful login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "cardNumber": "123456",
  "pin": "1111"
}

### Failed login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "cardNumber": "123456",
  "pin": "9999"
}

### Get Khasan accounts
GET http://localhost:8080/api/users/123456/accounts

### Get Alex accounts
GET http://localhost:8080/api/users/222222/accounts

### Get Maria accounts
GET http://localhost:8080/api/users/333333/accounts

### User not found
GET http://localhost:8080/api/users/999999/accounts


### Get checking balance
GET http://localhost:8080/api/accounts/1001/balance

### Get savings balance
GET http://localhost:8080/api/accounts/1002/balance

### Account not found
GET http://localhost:8080/api/accounts/9999/balance


### Deposit into checking account
POST http://localhost:8080/api/accounts/1001/deposit
Content-Type: application/json

{
  "amount": 100
}

### Invalid deposit amount
POST http://localhost:8080/api/accounts/1001/deposit
Content-Type: application/json

{
  "amount": -100
}

### Deposit into account not found
POST http://localhost:8080/api/accounts/9999/deposit
Content-Type: application/json

{
  "amount": 100
}


### Withdraw from checking account
POST http://localhost:8080/api/accounts/1001/withdraw
Content-Type: application/json

{
  "amount": 50
}

### Invalid withdrawal amount
POST http://localhost:8080/api/accounts/1001/withdraw
Content-Type: application/json

{
  "amount": -50
}

### Overdraft withdrawal
POST http://localhost:8080/api/accounts/1001/withdraw
Content-Type: application/json

{
  "amount": 10000
}

### Withdraw from account not found
POST http://localhost:8080/api/accounts/9999/withdraw
Content-Type: application/json

{
  "amount": 50
}


### Transfer from checking to savings
POST http://localhost:8080/api/transfer
Content-Type: application/json

{
  "fromAccountNumber": "1001",
  "toAccountNumber": "1002",
  "amount": 100
}

### Invalid transfer amount
POST http://localhost:8080/api/transfer
Content-Type: application/json

{
  "fromAccountNumber": "1001",
  "toAccountNumber": "1002",
  "amount": -100
}

### Transfer with insufficient funds
POST http://localhost:8080/api/transfer
Content-Type: application/json

{
  "fromAccountNumber": "1001",
  "toAccountNumber": "1002",
  "amount": 10000
}

### Transfer to same account
POST http://localhost:8080/api/transfer
Content-Type: application/json

{
  "fromAccountNumber": "1001",
  "toAccountNumber": "1001",
  "amount": 100
}

### Transfer with account not found
POST http://localhost:8080/api/transfer
Content-Type: application/json

{
  "fromAccountNumber": "1001",
  "toAccountNumber": "9999",
  "amount": 100
}